name: Build Test
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: setup python
        uses: actions/setup-python@v4
        with:
            python-version: 3.9

      - name: build
        run: pip install --no-cache-dir --upgrade -r requirements.txt
  Tox:
      needs: [Build]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: 3.9
        - name: tox
          run: |
            pip3 install tox
            tox -r
  Test:
      needs: [Tox]
      runs-on: ubuntu-latest
      env:
        TEST_POSTGRES_USER: testuser
        TEST_POSTGRES_PASSWORD: testpassword
        TEST_POSTGRES_DB: testdb
        TEST_SECRET_KEY: testsecretkey
      steps:
        - uses: actions/checkout@v4
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Build and start services
          run: |
            export POSTGRES_USER=${{ env.TEST_POSTGRES_USER }}
            export POSTGRES_PASSWORD=${{ env.TEST_POSTGRES_PASSWORD }}
            export POSTGRES_DB=${{ env.TEST_POSTGRES_DB }}
            export SECRET_KEY=${{ env.TEST_SECRET_KEY }}
            docker-compose up -d
        
        - name: Wait for the web service to be ready
          run: sleep 10

        - name: Curl endpoint on docker compose
          run: |
            curl --fail http://0.0.0.0:8000/ || exit 1

        - name: Shutdown
          run: docker-compose down