name: Build the docker compose app and test it.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out repository code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Setup env variables
      run: |
          export POSTGRES_USER=test-user
          export POSTGRES_PASSWORD=test-password
          export POSTGRES_DB=testdb
          export SECRET_KEY=testkey
      
    - name: Build and start services
      run: docker-compose up -d

    - name: Run tests
      run: |
        curl --fail http://localhost:8000/ || exit 1

    - name: Shutdown
      run: docker-compose down
